#!/bin/bash

# Path & Variables
_PROJECT_ROOT="/home/iiswc/workspace/workload-characterization-on-morello"
_LLAMA_CPP_PATH="/home/iiswc/workspace/llama-cpp"

# morello
_CHERI_MORELLO_CONNECT_IP=${1:-192.168.1.102}
_CHERI_MORELLO_CONNECT="iiswc@${_CHERI_MORELLO_CONNECT_IP}"
_CHERI_MORELLO_CONNECT_ROOT="root@${_CHERI_MORELLO_CONNECT_IP}"
_CHERI_MORELLO_RUN_DIR="/home/iiswc/llama-cpp"

RUN_FOLDERS=("build-cheribsd-morello-hybrid" "build-cheribsd-morello-purecap" "build-cheribsd-morello-purecap-benchmark")
BINARY_NAMES=("llama-bench" "llama-bench-matmult")

# project and expertiment results
_RESULTS_FOLDER="${2:-results/llama-cpp}"