#!/bin/bash
. "$(dirname "$0")/base"

for _type in "raw" "matmult"; do

cat <<EOF > _launch_pmcstat_${_type}
cd "\$(dirname "\$0")"

mkdir -p results_${_type} && \
cp ./_launch_${_type} ./results_${_type}/ && \
cd ./results_${_type} && \
rm -rf ./*pmcstat*.out ./*pmcstat*.gmon && \
rm -rf llama-bench.out llama-bench-matmult.*.out && \
chmod +x ./_launch_${_type}

./_launch_${_type} && sleep 15 && \
time ./_launch_${_type} > pmcstat.timing.out 2>&1 && sleep 15

pmcstat -d -P INST_RETIRED \
  -P CPU_CYCLES \
  -P STALL_BACKEND \
  -P STALL_FRONTEND \
  -P INST_SPEC \
  -P ASE_SPEC \
  -O pmcstat.S1.out -- ./_launch_${_type} && sleep 15 && \
  pmcstat -R pmcstat.S1.out -G pmcstat.S1.gmon && sleep 10

pmcstat -d -P BR_RETIRED \
  -P BR_MIS_PRED_RETIRED \
  -P BR_INDIRECT_SPEC \
  -P BR_RETURN_SPEC \
  -P BR_IMMED_SPEC \
  -O pmcstat.S2.out -- ./_launch_${_type} && sleep 15 && \
  pmcstat -R pmcstat.S2.out -G pmcstat.S2.gmon && sleep 10  

pmcstat -d -P ITLB_WALK \
  -P L1I_TLB_REFILL \
  -P L1I_TLB \
  -P L1I_CACHE \
  -P L1I_CACHE_REFILL \
  -P VFP_SPEC \
  -O pmcstat.S3.out -- ./_launch_${_type} && sleep 15 && \
  pmcstat -R pmcstat.S3.out -G pmcstat.S3.gmon && sleep 10

pmcstat -d -P DTLB_WALK \
  -P L1D_TLB \
  -P L1D_TLB_REFILL \
  -P L2D_TLB \
  -P L2D_TLB_REFILL \
  -P CRYPTO_SPEC \
  -O pmcstat.S4.out -- ./_launch_${_type} && sleep 15 && \
  pmcstat -R pmcstat.S4.out -G pmcstat.S4.gmon && sleep 10

pmcstat -d -P L1D_CACHE \
  -P L1D_CACHE_RD \
  -P L1D_CACHE_REFILL \
  -P L1D_CACHE_WR \
  -P LL_CACHE_MISS_RD \
  -P LL_CACHE_RD \
  -O pmcstat.S5.out -- ./_launch_${_type} && sleep 15 && \
  pmcstat -R pmcstat.S5.out -G pmcstat.S5.gmon && sleep 10

pmcstat -d -P L2D_CACHE \
  -P L2D_CACHE_RD \
  -P L2D_CACHE_REFILL \
  -P L2D_CACHE_ALLOCATE \
  -P L2D_CACHE_WR \
  -O pmcstat.S6.out -- ./_launch_${_type} && sleep 15 && \
  pmcstat -R pmcstat.S6.out -G pmcstat.S6.gmon && sleep 10

pmcstat -d -P MEM_ACCESS \
  -P MEM_ACCESS_RD \
  -P MEM_ACCESS_WR \
  -P LD_SPEC \
  -P ST_SPEC \
  -P DP_SPEC \
  -O pmcstat.S7.out -- ./_launch_${_type} && sleep 15 && \
  pmcstat -R pmcstat.S7.out -G pmcstat.S7.gmon && sleep 10

pmcstat -d -P MEM_ACCESS_RD_CTAG \
  -P MEM_ACCESS_WR_CTAG \
  -P CAP_MEM_ACCESS_RD \
  -P CAP_MEM_ACCESS_WR \
  -O pmcstat.S8.out -- ./_launch_${_type} && sleep 15 && \
  pmcstat -R pmcstat.S8.out -G pmcstat.S8.gmon && sleep 10
EOF

done

cat <<EOF > _launch_raw
script -q temp.out ../bin/llama-bench -m ${_CHERI_MORELLO_RUN_DIR}/models/7B/ggml-model-q8_0.gguf && cat temp.out >> llama-bench.out && rm temp.out
EOF

cat <<EOF > _launch_matmult
script -q temp.out ../bin/llama-bench-matmult -t 1 -i 50 && cat temp.out >> llama-bench-matmult.1threads.out && rm temp.out
script -q temp.out ../bin/llama-bench-matmult -t 2 -i 50 && cat temp.out >> llama-bench-matmult.2threads.out && rm temp.out
script -q temp.out ../bin/llama-bench-matmult -t 3 -i 50 && cat temp.out >> llama-bench-matmult.3threads.out && rm temp.out
script -q temp.out ../bin/llama-bench-matmult -t 4 -i 50 && cat temp.out >> llama-bench-matmult.4threads.out && rm temp.out
EOF

chmod +x _launch_raw _launch_matmult _launch_pmcstat_raw _launch_pmcstat_matmult

sed -i 's/pmcstat -d/pmcstat -n 1048576 -d/g' _launch_pmcstat_raw

for abi in purecap purecap-benchmark hybrid; do
    cp _launch_raw _launch_matmult _launch_pmcstat_raw _launch_pmcstat_matmult ${_LLAMA_CPP_PATH}/build-cheribsd-morello-${abi}
done

rm -rf _launch_raw _launch_matmult _launch_pmcstat_raw _launch_pmcstat_matmult