#!/bin/bash
. "$(dirname "$0")/base"

# source the SPEC environment
cd "${_SPECCPU_PATH}/../../" && source shrc && cd -

cat <<EOF > _launch_pmcstat

time ./_launch_raw > pmcstat.timing.out 2>&1 && sleep 15

pmcstat -d -P INST_RETIRED \
  -P CPU_CYCLES \
  -P STALL_BACKEND \
  -P STALL_FRONTEND \
  -P INST_SPEC \
  -P ASE_SPEC \
  -O pmcstat.S1.out -- ./_launch_raw && sleep 15 && \
  pmcstat -R pmcstat.S1.out -G pmcstat.S1.gmon && sleep 10

pmcstat -d -P BR_RETIRED \
  -P BR_MIS_PRED_RETIRED \
  -P BR_INDIRECT_SPEC \
  -P BR_RETURN_SPEC \
  -P BR_IMMED_SPEC \
  -O pmcstat.S2.out -- ./_launch_raw && sleep 15 && \
  pmcstat -R pmcstat.S2.out -G pmcstat.S2.gmon && sleep 10  

pmcstat -d -P ITLB_WALK \
  -P L1I_TLB_REFILL \
  -P L1I_TLB \
  -P L1I_CACHE \
  -P L1I_CACHE_REFILL \
  -P VFP_SPEC \
  -O pmcstat.S3.out -- ./_launch_raw && sleep 15 && \
  pmcstat -R pmcstat.S3.out -G pmcstat.S3.gmon && sleep 10

pmcstat -d -P DTLB_WALK \
  -P L1D_TLB \
  -P L1D_TLB_REFILL \
  -P L2D_TLB \
  -P L2D_TLB_REFILL \
  -P CRYPTO_SPEC \
  -O pmcstat.S4.out -- ./_launch_raw && sleep 15 && \
  pmcstat -R pmcstat.S4.out -G pmcstat.S4.gmon && sleep 10

pmcstat -d -P L1D_CACHE \
  -P L1D_CACHE_RD \
  -P L1D_CACHE_REFILL \
  -P L1D_CACHE_WR \
  -P LL_CACHE_MISS_RD \
  -P LL_CACHE_RD \
  -O pmcstat.S5.out -- ./_launch_raw && sleep 15 && \
  pmcstat -R pmcstat.S5.out -G pmcstat.S5.gmon && sleep 10

pmcstat -d -P L2D_CACHE \
  -P L2D_CACHE_RD \
  -P L2D_CACHE_REFILL \
  -P L2D_CACHE_ALLOCATE \
  -P L2D_CACHE_WR \
  -O pmcstat.S6.out -- ./_launch_raw && sleep 15 && \
  pmcstat -R pmcstat.S6.out -G pmcstat.S6.gmon && sleep 10

pmcstat -d -P MEM_ACCESS \
  -P MEM_ACCESS_RD \
  -P MEM_ACCESS_WR \
  -P LD_SPEC \
  -P ST_SPEC \
  -P DP_SPEC \
  -O pmcstat.S7.out -- ./_launch_raw && sleep 15 && \
  pmcstat -R pmcstat.S7.out -G pmcstat.S7.gmon && sleep 10

pmcstat -d -P MEM_ACCESS_RD_CTAG \
  -P MEM_ACCESS_WR_CTAG \
  -P CAP_MEM_ACCESS_RD \
  -P CAP_MEM_ACCESS_WR \
  -O pmcstat.S8.out -- ./_launch_raw && sleep 15 && \
  pmcstat -R pmcstat.S8.out -G pmcstat.S8.gmon && sleep 10

EOF

for bench in "${_BENCHMARKS[@]}"; do
    for label in "${LABELS[@]}"; do
        for size in "${SIZES[@]}"; do
            run_folder="run_base_${size}_${label}.0000"
            
            echo ${_SPECCPU_PATH}/${bench}/run/${run_folder}
            
            cp ./_launch_pmcstat ${_SPECCPU_PATH}/${bench}/run/${run_folder}/ && \
            cd ${_SPECCPU_PATH}/${bench}/run/${run_folder} && \
            specinvoke -n | grep -v "specinvoke exit" > ./_launch_raw && \
            chmod +x ./_launch_raw && \
            chmod +x ./_launch_pmcstat && cd - 

            case "$label" in
              "cheribsd-morello-hybrid-cheribuild_llvm")
                sed -i '1i export LD_LIBRARY_PATH=/home/iiswc/spec_run/openmp-hybrid:${LD_LIBRARY_PATH}' \
                  "${_SPECCPU_PATH}/${bench}/run/${run_folder}/_launch_raw"
                ;;
              
              "cheribsd-morello-purecap-benchmark-cheribuild_llvm")
                sed -i '1i export LD_LIBRARY_PATH=/home/iiswc/spec_run/openmp-purecap-benchmark:${LD_LIBRARY_PATH}' \
                  "${_SPECCPU_PATH}/${bench}/run/${run_folder}/_launch_raw"
                ;;
              
              "cheribsd-morello-purecap-cheribuild_llvm")
                sed -i '1i export LD_LIBRARY_PATH=/home/iiswc/spec_run/openmp-purecap:${LD_LIBRARY_PATH}' \
                  "${_SPECCPU_PATH}/${bench}/run/${run_folder}/_launch_raw"
                ;;
              
              *)
                echo "Unknown label: ${label}" >&2
                exit 1
                ;;
            esac

        done
    done
done

rm -rf _launch_pmcstat


# pprof --pdf ./imagick_r_base.ubuntu-llvm14 538.gprof > 538.gprof.pdf
# pmcstat -S all -O pmcstat.out
# pmcstat -S instructions -O pmcstat.out -- ./my_application
# Use the -G flag to create a gmon file for use with gprof:
# pmcstat -R pmcstat.out -G pmcstat.gmon
# gprof ./my_application pmcstat.gmon
# sudo pmcstat -P L1D_CACHE_RD -P STALL_BACKEND -P STALL_FRONTEND -P TTBR_WRITE_RETIRED -O pmcstat.out -- ./_launch_raw