#!/bin/bash

# Path & Variables
_SQLITE_BENCH_PATH="/home/iiswc/workspace/sqlite-bench"
_CONFIGS_FOLDER="/home/iiswc/workspace/workload-characterization-on-morello/configs"
_CHERI_PURECAP_CFG="${_CONFIGS_FOLDER}/cheribsd-morello-purecap.cfg"
_CHERI_HYBRID_CFG="${_CONFIGS_FOLDER}/cheribsd-morello-hybrid.cfg"
_CHERI_BENCHMARK_CFG="${_CONFIGS_FOLDER}/cheribsd-morello-purecap-benchmark.cfg"

# set environment variables
LLVM_DIR="/home/iiswc/cheri/build/morello-llvm-project-build"
LIBRARY_PATH=${LLVM_DIR}/lib:${LLVM_DIR}/lib32:${LIBRARY_PATH}  
LD_LIBRARY_PATH=${LLVM_DIR}/lib:${LLVM_DIR}/lib32:${LD_LIBRARY_PATH}
C_INCLUDE_PATH=${LLVM_DIR}/include:${C_INCLUDE_PATH}
CPLUS_INCLUDE_PATH=${LLVM_DIR}/include:${CPLUS_INCLUDE_PATH}

export CPATH=${_SQLITE_BENCH_PATH}:${CPATH} 

# Function to safely change directory
safe_cd() {
    cd "$1" || { echo "Failed to change to directory: $1"; exit 1; }
}