#!/bin/bash
. "$(dirname "$0")/base"

cat <<EOF > _launch_pmcstat
cd "\$(dirname "\$0")"

mkdir -p results && \
cp ./_launch_raw ./results/ && \
cd ./results && \
rm -rf ./*pmcstat*.out ./*pmcstat*.gmon && \
rm -rf run.out && \
chmod +x ./_launch_raw

./_launch_raw && sleep 15 && \
time ./_launch_raw > pmcstat.timing.out 2>&1 && sleep 15

pmcstat -d -P INST_RETIRED \
  -P CPU_CYCLES \
  -P STALL_BACKEND \
  -P STALL_FRONTEND \
  -P INST_SPEC \
  -P ASE_SPEC \
  -O pmcstat.S1.out -- ./_launch_raw && sleep 15 && \
  pmcstat -R pmcstat.S1.out -G pmcstat.S1.gmon && sleep 10

pmcstat -d -P BR_RETIRED \
  -P BR_MIS_PRED_RETIRED \
  -P BR_INDIRECT_SPEC \
  -P BR_RETURN_SPEC \
  -P BR_IMMED_SPEC \
  -O pmcstat.S2.out -- ./_launch_raw && sleep 15 && \
  pmcstat -R pmcstat.S2.out -G pmcstat.S2.gmon && sleep 10  

pmcstat -d -P ITLB_WALK \
  -P L1I_TLB_REFILL \
  -P L1I_TLB \
  -P L1I_CACHE \
  -P L1I_CACHE_REFILL \
  -P VFP_SPEC \
  -O pmcstat.S3.out -- ./_launch_raw && sleep 15 && \
  pmcstat -R pmcstat.S3.out -G pmcstat.S3.gmon && sleep 10

pmcstat -d -P DTLB_WALK \
  -P L1D_TLB \
  -P L1D_TLB_REFILL \
  -P L2D_TLB \
  -P L2D_TLB_REFILL \
  -P CRYPTO_SPEC \
  -O pmcstat.S4.out -- ./_launch_raw && sleep 15 && \
  pmcstat -R pmcstat.S4.out -G pmcstat.S4.gmon && sleep 10

pmcstat -d -P L1D_CACHE \
  -P L1D_CACHE_RD \
  -P L1D_CACHE_REFILL \
  -P L1D_CACHE_WR \
  -P LL_CACHE_MISS_RD \
  -P LL_CACHE_RD \
  -O pmcstat.S5.out -- ./_launch_raw && sleep 15 && \
  pmcstat -R pmcstat.S5.out -G pmcstat.S5.gmon && sleep 10

pmcstat -d -P L2D_CACHE \
  -P L2D_CACHE_RD \
  -P L2D_CACHE_REFILL \
  -P L2D_CACHE_ALLOCATE \
  -P L2D_CACHE_WR \
  -O pmcstat.S6.out -- ./_launch_raw && sleep 15 && \
  pmcstat -R pmcstat.S6.out -G pmcstat.S6.gmon && sleep 10

pmcstat -d -P MEM_ACCESS \
  -P MEM_ACCESS_RD \
  -P MEM_ACCESS_WR \
  -P LD_SPEC \
  -P ST_SPEC \
  -P DP_SPEC \
  -O pmcstat.S7.out -- ./_launch_raw
  pmcstat -R pmcstat.S7.out -G pmcstat.S7.gmon

pmcstat -d -P MEM_ACCESS_RD_CTAG \
  -P MEM_ACCESS_WR_CTAG \
  -P CAP_MEM_ACCESS_RD \
  -P CAP_MEM_ACCESS_WR \
  -O pmcstat.S8.out -- ./_launch_raw
  pmcstat -R pmcstat.S8.out -G pmcstat.S8.gmon
EOF

cat <<EOF > _launch_raw
if [ -f test.db ]; then   
    rm test.db
fi
../sqlite3 test.db < ../../suite.sql >> run.out 2>&1 && rm test.db
EOF

chmod +x _launch_raw _launch_pmcstat

mv _launch_raw _launch_pmcstat ${_PROJECT_ROOT}/sqlite-bench/binaries/